### ISSUE TITLE
How to scan barcode?

### ISSUE THREAD

**Issue by uokivan** [chitra16/QRScanner#1]
@chitra16 Thank you very much

I just to learn Obj-C, you sample is so good for me to know more about it,

But can you tell me , how to scan barcode ?

Thanks again

Ivan

**Comment by ChitralekhaYellewar** [comment]
Hi @uokivan,

I am glad that my QR Scan example in Obj-C was useful for you.

As this is QR Scanner, I have restricted the metadataObject output type obtained after the scan to "AVMetadataObjectTypeQRCode". 
_[In ViewController.m ([[metadataObject type]isEqualToString:AVMetadataObjectTypeQRCode]) ]_

If you want to scan Barcode, remove this.

Also, I have set MetadataObjectTypes to "AVMetadataObjectTypeQRCode" to restrict the scanning to QR codes only.

_[In ViewController.m, capturedMetadataOutput setMetadataObjectTypes: barCodeTypes];_

change it to below barcode types.

NSArray *barCodeTypes = @[AVMetadataObjectTypeUPCECode, AVMetadataObjectTypeCode39Code, AVMetadataObjectTypeCode39Mod43Code,
                              AVMetadataObjectTypeEAN13Code, AVMetadataObjectTypeEAN8Code, AVMetadataObjectTypeCode93Code, AVMetadataObjectTypeCode128Code,
                              AVMetadataObjectTypePDF417Code, AVMetadataObjectTypeQRCode, AVMetadataObjectTypeAztecCode];

And it will work for barcode scanning. 

I hope this will help. :)

**Comment by uokivan** [comment]
@chitra16 

![Screenshot 2019-06-04 at 11 43 24 AM](https://user-images.githubusercontent.com/23480211/58849725-05c1b580-86be-11e9-95e9-114e3e131d30.png)
Thank you so so much

but , because I just learn the xcode(obj-c), I get error, from my code...
can you tell me that , which part I wrong ?
Thanks so so much

Ivan

**Comment by ChitralekhaYellewar** [comment]
Hi Ivan,

you are using barCodeTypes array before you declared it. And the NSArray syntax is wrong. 
I would suggest you to check how to declare an array in Obj-C. :)

for now, just make it

NSArray *barCodeTypes = @[AVMetadataObjectTypeUPCECode, AVMetadataObjectTypeCode39Code, AVMetadataObjectTypeCode39Mod43Code,
AVMetadataObjectTypeEAN13Code, AVMetadataObjectTypeEAN8Code, AVMetadataObjectTypeCode93Code, AVMetadataObjectTypeCode128Code,
AVMetadataObjectTypePDF417Code, AVMetadataObjectTypeQRCode, AVMetadataObjectTypeAztecCode];

[captureMetadataOutput setMetadataObjectType: barCodeTypes];
